### ISSUE TITLE
Have Conn.Execute() wait for NLM_F_ACK when the request asked for one

### ISSUE THREAD

**Issue by tomparkin** [mdlayher/netlink#167]
When making a netlink request, the caller may ask for an ACK by setting `netlink.Acknowledge` in the message header.

Typically this is done for requests which don't return data, for example commands.  In this case the acknowledge usually contains an error code indicating the status of the command.

For information requests (e.g. retrieving state), an ACK is generally not asked for.  This is because the information request will (almost) always result in a response from the kernel.

If an ACK is asked for with an information request, the `netlink.Conn` instance will lose track of sequence numbers, as the ACK arrives as a separate message.

This paste of strace output demonstrates what happens:

https://pastebin.com/QmFudvru

The message with sequence number 241523028 is an information request which sets NLM_F_ACK.  Two responses are received for this request: the first on line 15 of the paste, a 192 byte message; and the second on line 18, the ACK message.

Note that there is a further sendmsg call interleaved between these messages: this is because Conn.Execute() treats the 192 byte message as the response for request 241523028, and returns to the caller.  A subsequent request with sequence number 241523029 then receives the ACK for 241523028, and Validate fails.  This state persists for the remainder of the lifetime of the `Conn` instance.

Since `Conn.Execute` has visibility of the request flags, it could be extended to wait for the ACK (scratch code for the purposes of demonstration only!):

```
func (c *Conn) Execute(message Message) ([]Message, error) {
    c.mu.Lock()    
    defer c.mu.Unlock()

    req, err := c.lockedSend(message)    
    if err != nil {    
        return nil, err    
    } 

    replies := []Message{}

again:
    rx, err := c.lockedReceive()
    if err != nil {
        return nil, err
    }

    if err := Validate(req, rx); err != nil {
        return nil, err
    }

    replies = append(replies, rx...)

    if (message.Header.Flags & Acknowledge) != 0 {
        var gotAck bool
        for _, m := range rx {
            if (m.Header.Flags & Acknowledge) != 0 {
                gotAck = true
            }
            if !gotAck {
                goto again
            }
        }
    }
    return replies, nil
}
```

**Comment by mdlayher** [comment]
Sounds good to me as discussed on Slack.

I am curious now if it makes sense to return Ack messages at all. In multipart messages for example, we strip the final "multipart done". When I use Ack in my packages, I typically ignore the returned messages anyway.

We could consider doing that here as well, but then that'd mean that Execute would sometimes `return nil, nil` which might be a little strange. Any thoughts on this, @acln0 and other folks?

**Comment by acln0** [comment]
I like this in principle because it feels like The Right Thing To Do, but it is a behavior change for `Execute`, and this package is at v1+ already, so I think we need to be careful.

It seems to me like this issue is arguing that current behavior of `Execute` is not very useful (or it even makes `Execute` hard / impossible to use correctly) when asking for acknowledgement. I don't use `Execute` in my own projects, so perhaps I am missing some nuance, but I think the issue is justified: something is not quite right here.

If we changed `Execute` to do this, I think we would need quite a bit of extra documentation for it (and the documentation is already long!):

* if message.Header.Flags & Acknowledge then we keep receiving until we see NLM_F_ACK
* we drop said ACK on the floor
* all of this means we can sometimes return `(nil, nil)`

I don't know if this should be `Execute` or if it should have another name. If this is still `Execute`, I also don't know if it's okay to change this and release it under a minor or patch version number. Can you think of code that worked before and is now broken because it sees `len(replies) == 0` when it was waiting for a reply with an acknowledgement? I don't have any such code in my own projects, but maybe someone else does.

In summary, I am unsure.

**Comment by mdlayher** [comment]
For brevity I will refer to `netlink.Acknowledge` as "Ack".

> I like this in principle because it feels like The Right Thing To Do, but it is a behavior change for Execute, and this package is at v1+ already, so I think we need to be careful.

Yep, this is a concern for me as well.

> It seems to me like this issue is arguing that current behavior of Execute is not very useful (or it even makes Execute hard / impossible to use correctly) when asking for acknowledgement.

I have typically used Execute with Ack when writing programs that configure the kernel, to verify that a change was applied. For example, when reconfiguring a WireGuard device, no output is normally produced. By asking for Ack, I can verify that my change took effect.

> Can you think of code that worked before and is now broken because it sees len(replies) == 0 when it was waiting for a reply with an acknowledgement? I don't have any such code in my own projects, but maybe someone else does.

I cannot. I will tag some other netlink users though: @terinjokes @ti-mo @hugelgupf @stapelberg @florianl 

---

In my mind here, there are three choices:

1) Make no code changes and document that passing Ack with Execute to an API that would normally return a message anyway (such as fetching kernel information) will result in weird behavior.

1) Add a special case to Execute: when issuing a request containing Ack, consume any number of responses until one of them contains Ack as well. Return any and all responses, as well as the Ack at the tail end of the slice, e.g. `[]netlink.Message{resp1, resp2, ack}

1) Add a special case to Execute: when issuing a request containing Ack, consume any number of responses until one of them contains Ack as well. **Discard the Ack at the tail end of the slice** and return the remaining responses, e.g. `[]netlink.Message{resp1, resp2 /* no more Ack */}`

---

I think adding documentation per Option 1 is reasonable regardless, to avoid the behavior that @tomparkin has experienced.

As for 2 and 3, I would like to hear from others as well. I suspect my own code would continue to work with either option, but it is possible that minor tweaks may need to be made at some call sites. Of course, this is indeed made trickier by the fact that we're already at v1, as mentioned by @acln0 .

**Comment by terinjokes** [comment]
Looking at my code: I only send Ack when running commands. When making requests that would normally return information, I don't send Ack.

For calls the calls that include Ack, I return error if `len(res) == 0`, but I make no attempts to parse any response. Since I use one netlink connection per goroutine, I don't expect options 2 and 3 to cause problems, but it could be surprising behavior.

**Comment by stapelberg** [comment]
In github.com/google/nftables, there are a number of mentions of netlink.Acknowledge, and we do use Execute.

I haven’t read this issue in detail, but if you give me a commit to apply, I can run the nftables tests and see if anything breaks (or you can run them yourself) :)

**Comment by florianl** [comment]
I'm also using the Acknowledge flag to make sure that a change was applied. But I don't expose this to the user of the package.
I'm slightly in favour for option 2 `[]netlink.Message{resp1, resp2, ack}`. If the user of the package asks for the acknowledge she/he should receive it.

**Comment by mdlayher** [comment]
I think at this point, it's probably for the best to leave this as is. The package has been in wide use for years and changing behaviors in subtle ways may confuse folks.
