### ISSUE TITLE
Error susses not handled, passed with other messages. 

### ISSUE THREAD

**Issue by brlbil** [mdlayher/netlink#70]
When receiving messages, checkMessage(m) checks for error messages. 
If the error message is 0x0 success it returns nil, this causes the error message to be propagated to the upper-level caller.

HeaderTypeDone messages are suppressed so I was wondering if this behavior intentional?
or should we fix it?

// receive is the internal implementation of Conn.Receive, which can be called
// recursively to handle multi-part messages.
func (c *Conn) receive() ([]Message, error) {
	[.......]
		if err := checkMessage(m); err != nil {
			return nil, err
		}
	}

**Comment by mdlayher** [comment]
> If the error message is 0x0 success it returns nil, this causes the error message to be propagated to the upper-level caller.

Can you clarify?  Are you asking if the message with leading success code should be returned with the success code attached?  This code path doesn't do any message modification.  I guess in my experience, I don't think I've ever had to trim off the success code from anything.

> HeaderTypeDone messages are suppressed so I was wondering if this behavior intentional?
or should we fix it?

It is intentional.  From what I can tell, they are just sentinels that indicate "no more messages" and don't contain any data.  That said, I wouldn't be surprised if some netlink family decided to put data in there anyway.

**Comment by SpComb** [comment]
> It is intentional. From what I can tell, they are just sentinels that indicate "no more messages" and don't contain any data. That said, I wouldn't be surprised if some netlink family decided to put data in there anyway.

The `NETLINK_CONNECTOR` family uses `NLMSG_DONE` with a payload: https://elixir.bootlin.com/linux/v4.15.12/source/samples/connector/ucon.c

This breaks using this library to implement the connector family, because `netlink:Conn.Receive()` will interpret the `struct cn_msg` payload as a `struct nlmsgerr`, and return an error.

**Comment by mdlayher** [comment]
PRs are welcome.

**Comment by mdlayher** [comment]
Ping @SpComb, I recently fixed an issue with wireguard genetlink and am curious if latest master with commit https://github.com/mdlayher/netlink/commit/9c29d56e3108b8b974f0f39c0d144c031972faf9#diff-a2ddca1600f34abb91244424f8431c2c fixes the issue.

If not, I can take another look at your package.

**Comment by mdlayher** [comment]
Closing due to lack of response. Feel free to reopen if need be.
